# plugin management
[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
# color,look and feel
# ==========================================================

[[plugins]]
repo = 'jonathanfilip/vim-lucius'
hook_post_source = 'source ~/.config/nvim/plugins/lucius.rc.vim'

# ==========================================================
# moving
# ==========================================================

# camel motion
[[plugins]]
repo = 'bkad/CamelCaseMotion'
hook_add = 'source ~/.config/nvim/plugins/CamelCaseMotion.rc.vim'

# ==========================================================
# editing
# ==========================================================

[[plugins]]
repo = 'tpope/vim-surround'
hook_add = '''
source ~/.config/nvim/plugins/vim-surround.rc.vim
'''

# ==========================================================
# completion
# ==========================================================


[[plugins]]
repo = 'cohama/lexima.vim'
