# plugiin magagement
[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
# color
# ==========================================================

# color scheme
[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
source ~/.config/nvim/plugins/iceberg.rc.vim
'''

# ==========================================================
# basic
# ==========================================================

# comment functions
[[plugins]]
repo = 'scrooloose/nerdcommenter'


# align
[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
source ~/.config/nvim/plugins/vim-easy-align.rc.vim
'''

[[plugins]]
repo = 'tpope/vim-surround'
hook_add = '''
source ~/.config/nvim/plugins/vim-surround.rc.vim
'''

# ==========================================================
# filter
# ==========================================================

# mru files
[[plugins]]
repo = 'Shougo/neomru.vim'

# fizzy finder
[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
hook_add = '''
source ~/.config/nvim/plugins/denite.rc.vim
'''

# fastest matcher
[[plugins]]
repo = 'nixprime/cpsm'
build = 'env PY3=ON ./install.sh'


