# ==========================================================
# programming
# ==========================================================

# golang
[[plugins]]
repo = 'zchee/deoplete-go'
depends = ['deoplete.nvim']
build = 'make'
hook_post_source = 'source ~/.config/nvim/plugins/deoplete-go.rc.vim'
on_ft = 'go'
