# plugiin magagement
[[plugins]]
repo = 'Shougo/dein.vim'

# ==========================================================
# color,look and feel
# ==========================================================

# status line
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'let g:airline_powerline_fonts = 1'

# status line
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# color scheme
[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = 'source ~/.config/nvim/plugins/iceberg.rc.vim'

# ==========================================================
# moving
# ==========================================================

# camel motion
[[plugins]]
repo = 'bkad/CamelCaseMotion'
hook_add = 'source ~/.config/nvim/plugins/CamelCaseMotion.rc.vim'

# ==========================================================
# editing
# ==========================================================

# comment functions
[[plugins]]
repo = 'scrooloose/nerdcommenter'

# align
[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = 'source ~/.config/nvim/plugins/vim-easy-align.rc.vim'

[[plugins]]
repo = 'tpope/vim-surround'
hook_add = '''
source ~/.config/nvim/plugins/vim-surround.rc.vim
'''

# ==========================================================
# completion
# ==========================================================

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'source ~/.config/nvim/plugins/vim-surround.rc.vim'

# ==========================================================
# filter
# ==========================================================

# minibufexplorer
[[plugins]]
repo = 'fholgado/minibufexpl.vim'
hook_add = ' source ~/.config/nvim/plugins/minibufexpl.rc.vim '


# mru files
[[plugins]]
repo = 'Shougo/neomru.vim'

# fizzy finder
[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
hook_add = 'source ~/.config/nvim/plugins/denite.rc.vim'

# fastest matcher
[[plugins]]
repo = 'nixprime/cpsm'
build = 'env PY3=ON ./install.sh'


# ==========================================================
# programming
# ==========================================================

# git
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = ' source ~/.config/nvim/plugins/gitgutter.rc.vim '
