# ==========================================================
# programming
# ==========================================================

# golang
[[plugins]]
repo = 'zchee/deoplete-go'
depends = ['deoplete.nvim']
build = 'make'
hook_post_source = 'source ~/.config/nvim/plugins/deoplete-go.rc.vim'
on_ft = 'go'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = 'source ~/.config/nvim/plugins/vim-go.rc.vim'
hook_post_source = 'source ~/.config/nvim/plugins/vim-go.post.rc.vim'

# ruby
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = '5t111111/denite-rails'
# repo = 'yuroyoro/denite-rails'
# rev = 'patch-1'
hook_post_source = 'source ~/.config/nvim/plugins/denite-rails.rc.vim'
on_ft = 'ruby'

# crystal
[[plugins]]
repo = 'rhysd/vim-crystal'
on_ft = 'crystal'
